Require filepath >= 1.4
Otherwise build fails with 
```
src/Development/Shake/Command.hs:464:35: error:
    • Variable not in scope: (-<.>) :: Bool -> String -> Bool
    • Perhaps you meant ‘<.>’ (imported from Development.Shake.FilePath)
    |
464 |     let progExe = if prog == prog -<.> exe then prog else prog <.> exe
    |                                   ^^^^
```